export const IS_IDENTICAL = 'IS_IDENTICAL'
export const IS_NOT_IDENTICAL = 'IS_NOT_IDENTICAL'
export const RESULT = 'RESULT'
export const NO_RESULT = 'NO_RESULT'
export const SWAPPED = 'SWAPPED'
export const NOT_SWAPPED = 'NOT_SWAPPED'
export const DIFF_ARRAY = 'DIFF_ARRAY'
